CREATE TABLE IF NOT EXISTS imagenes (
    id SERIAL PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL,
    ancho INTEGER NOT NULL,
    alto INTEGER NOT NULL,
    pixeles TEXT NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);